name: win32_browser_detect
description: This package detects the Windows default browser and returns the path to the exe.
version: 0.1.4
homepage: https://www.jhanley.com
repository: https://github.com/jhanley-com/win32_browser_detect

environment:
  sdk: ^3.1.0

platforms:
  windows:

# Add regular dependencies here.
dependencies:
  intl: '^0.18.1'
  io: '^1.0.4'
  win32_registry: '^1.1.1'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
